In [10]:
import tensorflow as tf

## 1.标量典型应用

如误差计算结果为标量


In [11]:
out=tf.random.uniform([4,10]) # 随机模拟网络输出
y=tf.constant([2,3,2,0]) # 随机构造样本真实标签
y_onehot=tf.one_hot(y,depth=10)
loss=tf.keras.losses.mse(y_onehot,out)
mean_loss=tf.reduce_mean(loss)
print(mean_loss)

tf.Tensor(0.28569013, shape=(), dtype=float32)


## 2.向量的典型应用

线性模型中的偏置层b就是向量

In [12]:
# z=Wx,模拟获得激活函数的输入z
z=tf.random.normal([4,2])
b=tf.zeros([2])
z+=b # 这里能直接相加是因为auto broadcast
print(z)

tf.Tensor(
[[ 1.5117668  -0.49642178]
 [-1.1269653   0.2386058 ]
 [-0.7498443   0.3158207 ]
 [ 1.4317056  -0.12876253]], shape=(4, 2), dtype=float32)


使用`Dense()`方式创建的网络层的偏置仍是向量

In [13]:
from tensorflow.keras import layers
fc=layers.Dense(5) # 创建一层Wx+b，输出节点为3
fc.build(input_shape=(4,3)) # 通过build函数创建W，b张量，输入节点为3
print(fc.bias) # 查看偏置向量

<tf.Variable 'bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>


## 3.矩阵
如全连接层的输入X形状为\[b,$d_{in}$\]，$d_{in}$为输入特征的长度，b表示输入样本的个数

In [14]:
X=tf.random.normal([2,4]) # 2个样本，特征长度为4
W=tf.ones([4,3]) # 全连接输出节点为3,
b=tf.zeros([3]) # 定义偏置向量
out=X@W+b
print(out)

tf.Tensor(
[[-0.16785419 -0.16785419 -0.16785419]
 [ 1.3512032   1.3512032   1.3512032 ]], shape=(2, 3), dtype=float32)


注：Dense()可直接构成一个全连接层$\sigma(X@W+b)$，而当$\sigma$为空时便是类似下面的线性层

In [15]:
fc=layers.Dense(3)
fc.build(input_shape=(2,4))
print(fc.kernel) # 查看权重矩阵



<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.8380239 ,  0.4526614 , -0.63739157],
       [-0.05694419, -0.90409404, -0.36676222],
       [-0.47348315,  0.8458489 ,  0.8170537 ],
       [ 0.5383004 , -0.9121868 , -0.4099993 ]], dtype=float32)>
