In [1]:
import tensorflow as tf

## 1.标量典型应用

如误差计算结果为标量


In [2]:
out=tf.random.uniform([4,10]) # 随机模拟网络输出
y=tf.constant([2,3,2,0]) # 随机构造样本真实标签
y_onehot=tf.one_hot(y,depth=10)
loss=tf.keras.losses.mse(y_onehot,out)
mean_loss=tf.reduce_mean(loss)
print(mean_loss)

tf.Tensor(0.32864687, shape=(), dtype=float32)


## 2.向量的典型应用

线性模型中的偏置层b就是向量

In [3]:
# z=Wx,模拟获得激活函数的输入z
z=tf.random.normal([4,2])
b=tf.zeros([2])
z+=b # 这里能直接相加是因为auto broadcast
print(z)

tf.Tensor(
[[ 0.27369753 -0.25807473]
 [-0.08883336  1.184936  ]
 [ 0.48938832  1.7196723 ]
 [ 0.13555428  1.1185842 ]], shape=(4, 2), dtype=float32)


使用`Dense()`方式创建的网络层的偏置仍是向量

In [4]:
from tensorflow.keras import layers
fc=layers.Dense(5) # 创建一层Wx+b，输出节点为3
fc.build(input_shape=(4,3)) # 通过build函数创建W，b张量，输入节点为3
print(fc.bias) # 查看偏置向量

<tf.Variable 'bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>


## 3.矩阵
如全连接层的输入X形状为\[b,$d_{in}$\]，$d_{in}$为输入特征的长度，b表示输入样本的个数

In [5]:
X=tf.random.normal([2,4]) # 2个样本，特征长度为4
W=tf.ones([4,3]) # 全连接输出节点为3,
b=tf.zeros([3]) # 定义偏置向量
out=X@W+b
print(out)

tf.Tensor(
[[-4.8178864 -4.8178864 -4.8178864]
 [ 2.0711055  2.0711055  2.0711055]], shape=(2, 3), dtype=float32)


注：Dense()可直接构成一个全连接层$\sigma(X@W+b)$，而当$\sigma$为空时便是类似下面的线性层

In [6]:
fc=layers.Dense(3)
fc.build(input_shape=(2,4))
print(fc.kernel) # 查看权重矩阵

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.8323802 , -0.79144245,  0.46062553],
       [ 0.58332396,  0.5645393 , -0.01869696],
       [ 0.37598026, -0.7486532 ,  0.7172103 ],
       [-0.5012189 ,  0.47896707,  0.6090678 ]], dtype=float32)>


## 4.三维张量

典型应用：表示序列信号

$$X=[b,\mathrm{sequence\ len},\mathrm{feature\ len}]$$

考虑NLP中评价句子是否为正面情绪的情感分类任务网络，通过IMDB数据集来演示如何表示句子

In [7]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.imdb.load_data(num_words=10000) # 自动加载IMDB电影评价数据集
x_train=tf.keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80) # 将句子填充、截断为等长80个单词的句子
print(x_train.shape)

/opt/julianApps/miniconda3/envs/tf38/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/opt/julianApps/miniconda3/envs/tf38/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


(25000, 80)


使用词向量将每个单词转换为长度为100的词向量

In [8]:
embedding=tf.keras.layers.Embedding(10000,100) # 创建词向量Embedding层类
out=embedding(x_train) # 将数字编码的单词转换为词向量
print(out.shape)



(25000, 80, 100)


## 5.四维张量

典型应用：保存特征图数据$[b,h,w,c]$

In [9]:
x=tf.random.normal([4,32,32,3]) # 创建彩色图片输入
layer=tf.keras.layers.Conv2D(16,kernel_size=3) # 创建一个卷积层
out=layer(x)
print(out.shape)

(4, 30, 30, 16)


In [ ]:
import os
pid=os.getpid()
!kill -9 $pid