In [1]:
import tensorflow as tf

## 1.填充

* 为何需要填充？各图片数据的高和宽、各序列信号的长度等，维度长度可能各不相同，为方便并行计算，需要将不同长度的数据扩张为相同数据。
* 复制操作可以扩展数据长度，但会破坏原有的数据的结构
* 解决方案是，在需要补充长度的开始或结束处填充足够数量的特定值（一般是无意义的值，如0），这种操作叫填充

假设有两个句子，并分别编码为：
* "I like the weather today." -> \[1,2,3,4,5,6\]
* "So do I." -> \[7,8,1,6\]

为保持编码长度一致，将第二个句子填充为\[7,8,1,6,0,0\]
此时再进行堆叠合并shape为\[2,6\]的张量

进行填充的关键函数：`tf.pad(x,paddings)`:
* paddings是包含了多个`[左边填充个数,右边填充个数]`的List。如`[[0,0],[2,1],[1,2]]`表示第一个维度不填充，第二个维度左边起始填充2个单元，右边结束处填充1个单元，第三个维度左边起始填充1个单元，右边结束处填充2个单元

In [2]:
a=tf.constant([1,2,3,4,5,6]) # 第一个句子
b=tf.constant([7,8,1,6]) # 第二个句子
b=tf.pad(b,[[0,2]]) # 句子末尾填充2个0
print(b)
c=tf.stack([a,b],axis=0) # 堆叠合并形成2个样本
print(c)

tf.Tensor([7 8 1 6 0 0], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 1 6 0 0]], shape=(2, 6), dtype=int32)


### 1.1.NLP中填充例子
* 自然语言处理中，数据集中的句子有长有短，一般选取能够覆盖大部分句子长度的阈值，如80个单词。
* 对于小于80个单词的句子，末尾填充0；大于80个单词的句子，截断尾部。

In [3]:
# 以IMDB数据集的加载为例
total_words=10000 # 设定词汇量大小
max_review_len=80 # 最大句子长度
embedding_len=100 # 词向量长度
# 加载IMDB数据集
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.imdb.load_data(num_words=total_words)
print(x_train.shape,x_test.shape)
# 将句子填充或截断到相同长度，设置为末尾填充和末尾截断方式
x_train=tf.keras.preprocessing.sequence.pad_sequences(x_train,maxlen=max_review_len,truncating='post',padding='post')
x_test=tf.keras.preprocessing.sequence.pad_sequences(x_test,maxlen=max_review_len,truncating='post',padding='post')
print(x_train.shape,x_test.shape)

/opt/julianApps/miniconda3/envs/tf38/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/opt/julianApps/miniconda3/envs/tf38/lib/python3.8/site-packages/tensorflow/python/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


(25000,) (25000,)
(25000, 80) (25000, 80)


### 1.2.图像中多个维度填充例子

如下图，是一个`[[0,0],[2,2],[2,2],[0,0]]`填充方案:

![](https://github.com/zfhxi/Learn_tensorflow/blob/master/ch05-TensorFlow%e8%bf%9b%e9%98%b6/img/03.png?raw=true)

In [4]:
x=tf.random.normal([4,28,28,1])
x_after_pad=tf.pad(x,[[0,0],[2,2],[2,2],[0,0]])
print(x_after_pad.shape)

(4, 32, 32, 1)


## 2.复制
同a04.08中复制数据一致，此处仅再做回顾：

In [5]:
x=tf.random.normal([4,32,32,3])
x_after_tile=tf.tile(x,[2,3,3,1]) # 图片数据复制一份，高宽各复制2份
print(x_after_tile.shape)

(8, 96, 96, 3)


In [ ]:
import os
pid=os.getpid()
!kill -9 $pid
