In [1]:
import tensorflow as tf

## 0.前言
考虑非线性激活函数ReLU，其可以通过简单的数据限幅运算实现（限制元素范围[0,$\infty$))

常见限幅：
* 下限幅: `tf.maximum(x,a)`, $x\in[a,+\infty)$
* 上限幅: `tf.minimum(x,a)`, $x\in(-\infty,a]$
* `tf.clip_by_value(x,min,max)`, $x\in[\mathrm{min},\mathrm{max}]$，也可通过`tf.minimum(tf.maximum(x,min),max)`组合实现

In [2]:
x=tf.range(9)
print(tf.maximum(x,2))
print(tf.minimum(x,7))
# 限制到2-7
print(tf.minimum(tf.maximum(x,2),7))

tf.Tensor([2 2 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 7], shape=(9,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 7], shape=(9,), dtype=int32)


In [ ]:
import os
pid=os.getpid()
!kill -9 $pid