In [1]:
import tensorflow as tf

## 0.总结

* TensorFlow中把标量、向量、矩阵统称为张量

## 1.标量创建

In [2]:
a=1.2 # python原生创建标量
aa=tf.constant(1.2) # tf方式创建
print(type(a))
print(aa)
print(type(aa))
print(tf.is_tensor(aa))

<class 'float'>
tf.Tensor(1.2, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
True


打印张量信息

In [3]:
x=tf.constant([1.2,3.3])
print(x)

tf.Tensor([1.2 3.3], shape=(2,), dtype=float32)


tensor转为numpy

In [4]:
x=tf.constant([1.2,3.3])
y=x.numpy()
print(y)
print(x)

[1.2 3.3]
tf.Tensor([1.2 3.3], shape=(2,), dtype=float32)


## 2.向量矩阵等的创建

* 向量的创建是给`tf.constant()`传递list

创建一个元素的向量

In [5]:
a=tf.constant([1.2])
print(a)
print(type(a))
print(a.shape)

tf.Tensor([1.2], shape=(1,), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1,)


创建3个元素的向量

In [6]:
a=tf.constant([1,2,3.])
print(a)
print(type(a))
print(a.shape)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3,)


创建矩阵

In [7]:
a=tf.constant([[1,2],[3,4]])
print(a)
print(type(a))
print(a.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)


创建3维张量

In [8]:
a=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(type(a))
print(a.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2, 2)


## 3.数值精度

* 位越长，精度越高，占用空间越大。
* 常用的精度类型有`tf.int16`,`tf.int64`,`tf.float16`,`tf.float32`,`tf.float64`（即`tf.double`）

In [9]:
a=tf.constant(123456789,dtype=tf.int16)
b=tf.constant(123456789,dtype=tf.int32)
print(a) # 精度低，溢出
print(b)

tf.Tensor(-13035, shape=(), dtype=int16)
tf.Tensor(123456789, shape=(), dtype=int32)


变量保存π

In [10]:
import numpy as np
pi_1=tf.constant(np.pi,dtype=tf.float32)
pi_2=tf.constant(np.pi,dtype=tf.float64)
print(pi_1)
print(pi_2)

tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592653589793, shape=(), dtype=float64)


## 4.精度转化

* 使用`tf.cast`进行类型转换

In [11]:
pi_3=tf.constant(np.pi,dtype=tf.float32)
print(pi_3)
if pi_3.dtype!=tf.float64:
    pi_4=tf.cast(pi_3,dtype=tf.float64)
print(pi_3)
print(pi_4)



tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.1415927410125732, shape=(), dtype=float64)


In [ ]:
import os
pid=os.getpid()
!kill -9 $pid