In [87]:
import tensorflow as tf
import numpy as np

## 1.从数组/列表对象创建

注：
* Numpy默认使用64位精度保存数据，转换到Tensor类型时精度为tf.float64，可在需要时转为tf.float32
* 实际上，`tf.constant()`和`tf.convert_to_tensor()`都能自动将Numpy数组和Python列表数据类型转为Tensor类型

In [88]:
# 从列表
a=tf.convert_to_tensor([1,2,3.])
print(a)
# 从数组
b=tf.convert_to_tensor(np.array([[1,2.],[3,4]]))
print(b)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)


## 2.创建全0或1的张量

创建全0或1的张量是很常见的操作。如在线性变换中，y=Wx+b，将W初始化为全1矩阵，b初始化为全0矩阵。

创建全0，全1的标量

In [89]:
W=tf.ones([])
b=tf.zeros([])
print(W)
print(b)

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


创建全0，全1的向量

In [90]:
W=tf.ones([1])
b=tf.zeros([1])
print(W)
print(b)

tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


创建全0，全1的矩阵

In [91]:
W=tf.ones([3,2])
b=tf.zeros([2,2])
print(W)
print(b)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


创建与其他变量形状相似的全0，全1张量

* 主要函数：`tf.zeros_like()`,`tf.ones_like()`

In [92]:
a=np.linspace(1,24,6)
a=a.reshape((3,2))
A=tf.convert_to_tensor(a)
print(A)

W=tf.ones_like(A)
# W1=tf.ones(A.shape)
b=tf.zeros_like(A)
# b1=tf.zeros(A.shape)
print(W)
# print(W1)
print(b)
# print(b1)

tf.Tensor(
[[ 1.   5.6]
 [10.2 14.8]
 [19.4 24. ]], shape=(3, 2), dtype=float64)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float64)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float64)


## 3.创建自定义数值的张量

主要函数为：`tf.fill()`，初始化为指定值

In [93]:
# 创建元素为-1的标量
print(tf.fill([],-1))
# 创建长度为4、所有元素为-2的向量
print(tf.fill([4],-2))
# 创建所有元素为99的矩阵
print(tf.fill([2,2],99))

tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor([-2 -2 -2 -2], shape=(4,), dtype=int32)
tf.Tensor(
[[99 99]
 [99 99]], shape=(2, 2), dtype=int32)


## 4.创建已知分布的张量

1. 正太分布: `tf.random.normal(shape,mean=0.0,stddev=1.0)`
2. 均匀分布: `tf.random.uniform(shape,minval=0.0,maxval=None,dtype=tf.float32)`， For floats, the default range is [0, 1). For ints, at least maxval must be specified explicitly.


In [94]:
# 正太分布
a=tf.random.normal(shape=[2,2],mean=1.,stddev=2.)
print(a)

# 均匀分布
b=tf.random.uniform([2,2],minval=0,maxval=10)
print(b)
b1=tf.random.uniform([2,2],maxval=100,dtype=tf.int32)
print(b1)

tf.Tensor(
[[ 0.878792   0.9604731]
 [ 1.617727  -0.984781 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[7.1574316 2.995714 ]
 [5.307251  1.4103305]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[30 40]
 [29 16]], shape=(2, 2), dtype=int32)


## 5.创建序列

主要函数：
* `tf.range(limit,delta=1)`来创建[0,limit)之间、步长为delta的整型序列
* `tf.range(start,limit,delta=1)`来创建[start,limit)之间、步长为delta的整型序列

In [95]:
a=tf.range(10,delta=2)
print(a)
b=tf.range(50,100,2)
print(b)


tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor(
[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98], shape=(25,), dtype=int32)
