In [1]:
import tensorflow as tf

## 1.加减乘除运算
* `tf.add`,`tf.subtract`,`tf.multiply`,`tf.divide`分别与`+-*/`对应
* 整除和余除:`//`、`%`

In [2]:
# 整除
a=tf.range(5)
b=tf.constant(2)
print(a//b)
print(a%b)

tf.Tensor([0 0 1 1 2], shape=(5,), dtype=int32)
tf.Tensor([0 1 0 1 0], shape=(5,), dtype=int32)


## 2.乘方运算
实现$y=x^a$:
* `tf.pow(x,a)`
* `x**a`

In [3]:
x=tf.range(4)
print(tf.pow(x,3))
print(x**2)
x1=tf.constant([1.,4.,9.])
print(x1**.5)

tf.Tensor([ 0  1  8 27], shape=(4,), dtype=int32)
tf.Tensor([0 1 4 9], shape=(4,), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


其他乘方运算：
* `tf.square(x)`
* `tf.sqrt(x)`，x必须为浮点数

In [4]:
# 平方
print(tf.square(4)==4**2)
print(tf.sqrt(4.)==4.**.5)

tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)


## 3.指数和对数运算
实现$y=a^x$:
* `tf.pow(a,x)`
* `a**x`


In [5]:
# 指数运算
x=tf.constant([1.,2.,3.])
print(2**x)

tf.Tensor([2. 4. 8.], shape=(3,), dtype=float32)


对于自然指数$e^x$，可通过`tf.exp(x)`实现：

In [6]:
print(tf.exp(2.))

tf.Tensor(7.389056, shape=(), dtype=float32)


对于自然对数，可以通过`tf.math.log(x)`实现：

In [7]:
x=tf.exp(8.9)
y=tf.math.log(x)
print(y)

tf.Tensor(8.9, shape=(), dtype=float32)


对于其他底数的对数，通过换底公式:

$$\mathrm{log}_ax=\frac{\mathrm{log}_ex}{\mathrm{log}_ea}$$

如计算$\mathrm{log}_{10}x$：

In [8]:
x=tf.constant([2.,3.4])
x1=10**x
print(tf.math.log(x1)/tf.math.log(10.))

tf.Tensor([2.  3.4], shape=(2,), dtype=float32)


## 4.矩阵相乘运算

矩阵相乘的实现：
* `A@B`
* `tf.matmul(A,B)`

>需要注意的是,TensorFlow中的矩阵相乘可以使用批量方式,也就是张量A和B的维度数可以大于2。
> 当张量A和B维度数大于2时,TensorFlow会选择A和B的最后两个维度进行矩阵相乘,前面所有的维度都视作Batch维度

In [9]:
A=tf.random.normal([4,3,28,32])
B=tf.random.normal([4,3,32,2])
C=A@B
print(C.shape)

(4, 3, 28, 2)


矩阵相乘同样支持自动

Broadcasting机制

In [10]:
A=tf.random.normal([4,28,32])
B=tf.random.normal([32,16])
C=A@B
print(C.shape)

(4, 28, 16)


上述运算，先将B扩展为shape为\[4,32,16\]，再与A相乘

In [ ]:
import os
pid=os.getpid()
!kill -9 $pid

