## Eager执行
参考:<https://zhuanlan.zhihu.com/p/70232196>

In [1]:
import tensorflow as tf

在eager执行下，每个操作后的返回值是tf.Tensor

In [2]:
x=tf.ones((2,2),dtype=tf.dtypes.float32)
y=tf.constant([[1,2],
               [3,4]],dtype=tf.dtypes.float32)
z=tf.matmul(x,y)
print(z)
print(z.numpy())

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)
[[4. 6.]
 [4. 6.]]


这种eager执行的另外一个好处是可以使用Python原生功能，比如下面的条件判断：

In [3]:
random_value=tf.random.uniform([],0,1)
x1=tf.reshape(tf.range(0,4),[2,2])
print(random_value)
if random_value.numpy()>0.5:
    y1=tf.matmul(x1,x1)
else:
    y1=tf.add(x1,x1)
print(y1)

tf.Tensor(0.45175254, shape=(), dtype=float32)
tf.Tensor(
[[0 2]
 [4 6]], shape=(2, 2), dtype=int32)


另外一个重要的问题，在egaer模式下如何计算梯度。
* 在Graph模式时，我们在构建模型前向图时，同时也会构建梯度图，这样实际喂数据执行时可以很方便计算梯度。
* 但是eager执行是动态的，这就需要每一次执行都要记录这些操作以计算梯度，这是通过tf.GradientTape来追踪所执行的操作以计算梯度，下面是一个计算实例：

In [4]:
w=tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss=w*w+2.*w+5.
grad=tape.gradient(loss,w)
print(grad)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
import os

pid = os.getpid()
print(pid)
!kill -9 $pid

3039
